# Generated by Django 4.1.7 on 2023-03-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('total_trips', models.IntegerField(default=0)),
                ('upcoming_trips', models.IntegerField(default=0)),
                ('total_distance', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
