# Generated by Django 4.1.7 on 2023-03-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='total_trips',
            field=models.IntegerField(default=1),
        ),
    ]
