# Generated by Django 4.1.7 on 2023-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
